### ISSUE TITLE
HTML Build Run Error

### ISSUE THREAD

**Issue by apps-adil** [Jorge-SunSpirit/Doki-Doki-Takeover#9]
Currently, I have a domain with the newest HTML build uploaded to it, but when I run it it says

Uncaught TypeError: c is not a function
    at Function.sa.init (DokiTakeover.js:3534:380)
    at Function.Kb.connect (DokiTakeover.js:523:120)
    at Zf.create (DokiTakeover.js:1021:285)
    at wj.switchState (DokiTakeover.js:1167:213)
    at wj.create (DokiTakeover.js:1163:185)
    at wj.__dispatchEvent (DokiTakeover.js:117:153)
    at wj.__dispatchEvent (DokiTakeover.js:132:166)
    at wj.__dispatchWithCapture (DokiTakeover.js:133:152)
    at wa.addChildAt (DokiTakeover.js:160:336)
    at wa.addChild (DokiTakeover.js:158:353)

Can someone help?

**Comment by ActualMandM** [comment]
Yea, HTML5 is broken due to GameJolt stuff updating, the next update currently has GameJolt related stuff disabled

**Comment by ActualMandM** [comment]
I've removed the HTML5 builds from the recent releases, you can make a working build by disabling `FEATURE_GAMEJOLT` in Project.xml

**Comment by ActualMandM** [comment]
I've added a new HTML5 build with the GameJolt integration disabled to the latest 2.0.7 release.

![2022-02-28_18-23-16_vivaldi](https://user-images.githubusercontent.com/15317421/156093602-e8b9a3c7-f353-44fb-8340-edf05ff6dc4b.png)
